version: '3'

services:
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  python-3.12-sticky_deploy_it:
    image: mcr.microsoft.com/devcontainers/python:3.12
    container_name: sticky_deploy_it-${USER}-python-3.12
    volumes:
      - ../:/workspaces/sticky_deploy_it:cached
    command: sleep infinity

    env_file:
      - ./devcontainer.env
    security_opt:
      - no-new-privileges:true
    networks:
      - sticky_deploy_it-network

networks:
  sticky_deploy_it-network:
    name: sticky_deploy_it-${USER}-network
